export interface Product {
  id: number;
  name: string;
  price: number;
  image: string;
  images: string;
  description: string;
  category: string;
  stock: number;
  sku: string | null;
  supplier: string | null;
  supplierUrl: string | null;
  costPrice: number | null;
}

export const products: Product[] = [
  {
    id: 1,
    name: "Ampharos",
    price: 7.0,
    image: "/images/products/1-ampharos.png",
    images: JSON.stringify(["/images/products/back/1-ampharos-back.jpg"]),
    description: "Carta Ampharos del set Ascended Heroes / Ninja Spinner (JP). #88/83 Secret Rare. En excelente estado. Precio según lista del cliente: $7.",
    category: "Cartas",
    stock: 25,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 2,
    name: "Banette",
    price: 2.0,
    image: "/images/products/2-banette.png",
    images: JSON.stringify(["/images/products/back/2-banette-back.pdf", "/images/products/detail/2-banette-detail.pdf"]),
    description: "Carta Banette del set Ascended Heroes. #32/108. Precio según lista del cliente: $2. Gran opción para mazos de tipo psíquico.",
    category: "Cartas",
    stock: 30,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 3,
    name: "Crobat",
    price: 4.0,
    image: "/images/products/3-crobat.png",
    images: JSON.stringify(["/images/products/back/3-crobat-back.jpg", "/images/products/detail/3-crobat-detail.jpg"]),
    description: "Carta Crobat del set Ascended Heroes / Chaos Rising. #93/86 Illustration Rare. Precio según lista del cliente: $4.",
    category: "Cartas",
    stock: 20,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 4,
    name: "Eevee",
    price: 3.0,
    image: "/images/products/4-eevee.png",
    images: JSON.stringify(["/images/products/back/4-eevee-back.jpg", "/images/products/detail/4-eevee-detail.pdf"]),
    description: "Carta Eevee del set Ascended Heroes / Plasma Freeze. #89/116. El Pokémon más querido por los coleccionistas.",
    category: "Cartas",
    stock: 35,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 5,
    name: "Holon's Magnemite",
    price: 2.5,
    image: "/images/products/5-magnemite.png",
    images: JSON.stringify(["/images/products/back/5-magnemite-back.pdf", "/images/products/detail/5-magnemite-detail.jpg"]),
    description: "Carta Holon's Magnemite del set Delta Species (EX). Edición clásica con diseño retro.",
    category: "Cartas",
    stock: 22,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 6,
    name: "Mega Pyroar EX",
    price: 4.0,
    image: "/images/products/6-mega-pyroar.png",
    images: JSON.stringify(["/images/products/back/6-mega-pyroar-back.jpg", "/images/products/detail/6-mega-pyroar-detail.jpg"]),
    description: "Carta Mega Pyroar EX del set Ascended Heroes / Chaos Rising. #15/86 Double Rare.",
    category: "Cartas",
    stock: 15,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 7,
    name: "Starmie",
    price: 1.0,
    image: "/images/products/7-starmie.png",
    images: JSON.stringify(["/images/products/back/7-starmie-back.jpg", "/images/products/detail/7-starmie-detail.jpg"]),
    description: "Carta Starmie Base Set. #64/102 Common. Clásica carta de agua en excelente estado.",
    category: "Cartas",
    stock: 40,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 8,
    name: "Tangela",
    price: 5.0,
    image: "/images/products/8-tangela.png",
    images: JSON.stringify(["/images/products/back/8-tangela-back.pdf", "/images/products/detail/8-tangela-detail.jpg"]),
    description: "Carta Tangela Base Set. #66/102 Common. Pieza coleccionable de las primeras ediciones.",
    category: "Cartas",
    stock: 18,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 9,
    name: "Pikachu",
    price: 8.0,
    image: "/images/products/pikachu.png",
    images: JSON.stringify([]),
    description: "Carta Pikachu (Portada Principal). El ícono de Pokémon en versión coleccionable.",
    category: "Cartas",
    stock: 12,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 10,
    name: "Team Rocket's Dark Pokemon",
    price: 12.0,
    image: "/images/products/rockets.png",
    images: JSON.stringify([]),
    description: "Carta del set Team Rocket. Pokémon Oscuros clásicos de la era 2000.",
    category: "Cartas",
    stock: 8,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 11,
    name: "Venonat",
    price: 3.0,
    image: "/images/products/venonat.png",
    images: JSON.stringify([]),
    description: "Carta Venonat Base Set / Jungle. #56 Common.",
    category: "Cartas",
    stock: 28,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 12,
    name: "Mega Greninja EX",
    price: 25.0,
    image: "/images/products/mega-grenninja.png",
    images: JSON.stringify([]),
    description: "Carta Mega Greninja EX (BREAKthrough / Chaos Rising). Chase card del set.",
    category: "Cartas",
    stock: 5,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 13,
    name: "Grovyle",
    price: 5.0,
    image: "/images/products/grovyle.png",
    images: JSON.stringify([]),
    description: "Carta Grovyle (Ruby & Sapphire era). Evolución media de Treecko.",
    category: "Cartas",
    stock: 16,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 14,
    name: "Omanyte",
    price: 4.0,
    image: "/images/products/52.png",
    images: JSON.stringify([]),
    description: "Carta Omanyte Fossil Set. #52/62 Uncommon.",
    category: "Cartas",
    stock: 20,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 15,
    name: "Piplup",
    price: 4.0,
    image: "/images/products/piplup.png",
    images: JSON.stringify([]),
    description: "Carta Piplup (Diamond & Pearl era). Starter de agua de Sinnoh.",
    category: "Cartas",
    stock: 22,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 16,
    name: "Doduo",
    price: 2.0,
    image: "/images/products/42.png",
    images: JSON.stringify([]),
    description: "Carta Doduo Base Set. #42/102 Common.",
    category: "Cartas",
    stock: 30,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 17,
    name: "Aerodactyl",
    price: 18.0,
    image: "/images/products/aerodacty.png",
    images: JSON.stringify([]),
    description: "Carta Aerodactyl Fossil Set. #4/62 Holo Rare.",
    category: "Cartas",
    stock: 7,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 18,
    name: "Dawn (Supporter)",
    price: 6.0,
    image: "/images/products/dawn.png",
    images: JSON.stringify([]),
    description: "Carta de Entrenador: Dawn (Amanecer). Supporter del set Diamond & Pearl.",
    category: "Cartas",
    stock: 14,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 19,
    name: "Booster Bundle",
    price: 47.0,
    image: "/images/products/9-booster-bundle.png",
    images: JSON.stringify(["/images/products/detail/9-booster-detail.jpg", "/images/products/ascended/9-booster-bundle-alt.jpg"]),
    description: "Booster Bundle completo (6 sobres). Precio sugerido retail: $26.94 USD (~$485 MXN).",
    category: "Box",
    stock: 10,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 20,
    name: "Booster Bundle Ascended Heroes",
    price: 52.0,
    image: "/images/products/10-booster-ascended.png",
    images: JSON.stringify(["/images/products/ascended/9-booster-bundle-alt.jpg"]),
    description: "Booster Bundle del set Ascended Heroes (Mega Evolution - Ascended Heroes, enero 2026). 295+ cartas.",
    category: "Box",
    stock: 8,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 21,
    name: "Elite Trainer Box (ETB)",
    price: 52.0,
    image: "/images/products/11-etb.png",
    images: JSON.stringify(["/images/products/detail/11-etb-detail.png", "/images/products/ascended/11-etb-alt.png"]),
    description: "Elite Trainer Box estándar (9 sobres + accesorios). MSRP: $45-55 USD.",
    category: "Box",
    stock: 6,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 22,
    name: "ETB Ascended Heroes",
    price: 58.0,
    image: "/images/products/12-etb-ascended.png",
    images: JSON.stringify(["/images/products/ascended/11-etb-alt.png"]),
    description: "Elite Trainer Box Ascended Heroes (Edición Especial 2026). Contenido exclusivo.",
    category: "Box",
    stock: 5,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 23,
    name: "Sleeved Booster Pack",
    price: 5.0,
    image: "/images/products/13-sleeved-pack.png",
    images: JSON.stringify(["/images/products/detail/13-sleeved-detail.jpg", "/images/products/detail/13-sobre-detail.jpg"]),
    description: "Sobre booster individual con funda protectora. MSRP: $4.49-5.49 USD.",
    category: "Box",
    stock: 50,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 24,
    name: "Sobre Suelto (Booster Pack)",
    price: 5.0,
    image: "/images/products/sobre.jpg",
    images: JSON.stringify(["/images/products/detail/13-sobre-detail.jpg"]),
    description: "Sobre booster individual suelto. MSRP: $4.49-4.99 USD.",
    category: "Box",
    stock: 45,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 25,
    name: "Funko Pop! Michael Jackson Thriller #359",
    price: 15.0,
    image: "/images/products/funko/funko-MJ.png",
    images: JSON.stringify([]),
    description: "Funko Pop! Rocks: Michael Jackson (Thriller) #359. Vinyl figure 9cm.",
    category: "Funko",
    stock: 10,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 26,
    name: "Funko Pop! Overwatch McCree / Cassidy #182",
    price: 13.0,
    image: "/images/products/funko/funko-McCree.png",
    images: JSON.stringify([]),
    description: "Funko Pop! Games: Overwatch - McCree (ahora Cassidy) #182. GameStop Exclusive.",
    category: "Funko",
    stock: 12,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 27,
    name: "Funko Pop! Haikyuu!! Shishio",
    price: 13.0,
    image: "/images/products/funko/funko-shishido.png",
    images: JSON.stringify([]),
    description: "Funko Pop! Animation: Haikyuu!! - Shishio (Nekoma).",
    category: "Funko",
    stock: 14,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 28,
    name: "Funko Pop! Star Wars Sabine Wren #135",
    price: 14.0,
    image: "/images/products/funko/funko-sabine.png",
    images: JSON.stringify([]),
    description: "Funko Pop! Star Wars: Rebels - Sabine Wren #135.",
    category: "Funko",
    stock: 11,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 29,
    name: "Funko Pop! Hunter x Hunter Bisky #1133",
    price: 13.0,
    image: "/images/products/funko/funko-bisky.png",
    images: JSON.stringify([]),
    description: "Funko Pop! Animation: Hunter x Hunter - Biscuit Kreuger (Bisky) #1133.",
    category: "Funko",
    stock: 13,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 30,
    name: "Funko Pop! My Hero Academia Tsuyu Asui #374",
    price: 13.0,
    image: "/images/products/funko/funko-tsuyu.png",
    images: JSON.stringify([]),
    description: "Funko Pop! Animation: My Hero Academia - Tsuyu Asui (Froppy) #374.",
    category: "Funko",
    stock: 15,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 31,
    name: "Funko Pop! (Genérico / Sorpresa)",
    price: 13.0,
    image: "/images/products/funko/funko.png",
    images: JSON.stringify([]),
    description: "Funko Pop! sorpresa. Modelo aleatorio de nuestra colección.",
    category: "Funko",
    stock: 20,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 32,
    name: "Promo Ascended Heroes",
    price: 18.0,
    image: "/images/products/promos/Ascended- heroes.png",
    images: JSON.stringify([]),
    description: "Promoción del set Ascended Heroes (Mega Evolution).",
    category: "Promociones",
    stock: 25,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 33,
    name: "Promo Black Bolt",
    price: 22.0,
    image: "/images/products/promos/Black-bolt.png",
    images: JSON.stringify([]),
    description: "Promoción del set Black Bolt. Colección exclusiva.",
    category: "Promociones",
    stock: 18,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 34,
    name: "Promo Chaos Rising",
    price: 20.0,
    image: "/images/products/promos/Chaos-Rising.png",
    images: JSON.stringify([]),
    description: "Promoción del set Chaos Rising. Mega Evolutions y cartas raras.",
    category: "Promociones",
    stock: 20,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 35,
    name: "Promo Destined Rivals",
    price: 25.0,
    image: "/images/products/promos/Destined-rivals.png",
    images: JSON.stringify([]),
    description: "Promoción del set Destined Rivals.",
    category: "Promociones",
    stock: 15,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 36,
    name: "Promo Estellar Crown",
    price: 19.0,
    image: "/images/products/promos/Estellar-Crown.png",
    images: JSON.stringify([]),
    description: "Promoción del set Estellar Crown.",
    category: "Promociones",
    stock: 22,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 37,
    name: "Promo Journey Together",
    price: 17.0,
    image: "/images/products/promos/Journey-Together.png",
    images: JSON.stringify([]),
    description: "Promoción del set Journey Together.",
    category: "Promociones",
    stock: 24,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 38,
    name: "Promo Mega Evolution",
    price: 28.0,
    image: "/images/products/promos/Mega-Evolution.png",
    images: JSON.stringify([]),
    description: "Promoción del set Mega Evolution.",
    category: "Promociones",
    stock: 10,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 39,
    name: "Promo Perfect Order",
    price: 16.0,
    image: "/images/products/promos/Perfect-Order.png",
    images: JSON.stringify([]),
    description: "Promoción del set Perfect Order.",
    category: "Promociones",
    stock: 26,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 40,
    name: "Promo Phantasmal Flame",
    price: 21.0,
    image: "/images/products/promos/Phantasmal-flame.png",
    images: JSON.stringify([]),
    description: "Promoción del set Phantasmal Flame.",
    category: "Promociones",
    stock: 19,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 41,
    name: "Promo Pitch Black",
    price: 23.0,
    image: "/images/products/promos/Pitch-Black.png",
    images: JSON.stringify([]),
    description: "Promoción del set Pitch Black.",
    category: "Promociones",
    stock: 17,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 42,
    name: "Promo Prismatic Evolutions",
    price: 30.0,
    image: "/images/products/promos/Prismatic-Evolutions.png",
    images: JSON.stringify([]),
    description: "Promoción del set Prismatic Evolutions.",
    category: "Promociones",
    stock: 8,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 43,
    name: "Promo Scarlet & Violet",
    price: 24.0,
    image: "/images/products/promos/Scarlet  y Violet.png",
    images: JSON.stringify([]),
    description: "Promoción del set Scarlet & Violet.",
    category: "Promociones",
    stock: 16,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 44,
    name: "Promo Shrouded Fable",
    price: 18.0,
    image: "/images/products/promos/Shrouded-Flave.png",
    images: JSON.stringify([]),
    description: "Promoción del set Shrouded Fable.",
    category: "Promociones",
    stock: 21,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 45,
    name: "Promo Surging Sparks",
    price: 26.0,
    image: "/images/products/promos/Surging-Sparks.png",
    images: JSON.stringify([]),
    description: "Promoción del set Surging Sparks.",
    category: "Promociones",
    stock: 12,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
  {
    id: 46,
    name: "Promo White Flare",
    price: 20.0,
    image: "/images/products/promos/White-Flare.png",
    images: JSON.stringify([]),
    description: "Promoción del set White Flare.",
    category: "Promociones",
    stock: 19,
    sku: null,
    supplier: null,
    supplierUrl: null,
    costPrice: null,
  },
];

export { products as allProducts };

export function getProducts(): Product[] {
  return products;
}

export function getProductById(id: number): Product | undefined {
  return products.find((p) => p.id === id);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q)
  );
}
